spring:
  profiles:
   active: real, real-db
   #active: local
  devtools:
    restart:
      enabled: true
      additional-paths: classpath:/
    livereload:
      enabled: true
    mustache:
      cache: false
logging:
  level:
    root: info